project:
  type: book
  output-dir: docs 

book:
  title: "Cellestial"
  author: "Zafer Kosar"
  date: "25/11/2024"
  chapters:
    - index.qmd
    - part: Introduction
      chapters:
        - examples/00_overview.ipynb
    - part: Dimensional Reduction
      chapters:
        - examples/dimensional/01_umap.ipynb
        - examples/dimensional/01_umaps.ipynb
        - examples/dimensional/02_tsne.ipynb
        - examples/dimensional/02_tsnes.ipynb
        - examples/dimensional/03_pca.ipynb
        - examples/dimensional/03_pcas.ipynb
    - part: Distribution
      chapters:
        - examples/distribution/01_violin.ipynb
        - examples/distribution/01_violins.ipynb
        - examples/distribution/02_boxplot.ipynb
        - examples/distribution/02_boxplots.ipynb
  page-footer: "Copyright 2024, Zafer Kosar"
  page-navigation: true
  navbar:
    logo: assets/cellestial_logo.png
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/DataVil/Cellestial


format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    highlight-style: github-light
    monofont: "JetBrainsMonoSemiBold"
    code-fold: false
    css: custom.css
    code-copy: true


    
