[project]
name = "cellestial"
version = "0.47.1"
description = ""
authors = [
    { name = "Zaf4", email = "zafermolbio@gmail.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11,<4.0"
dependencies = [
    "anndata>=0.10.8,<1.0",
    "lets-plot>=4.9.0,<5.0.0",
    "polars[pyarrow]>=1.30.0,<2.0.0",
    "scikit-image>=0.23.1,<1.0",
    "spatialdata>=0.7,<1.0",
    "tqdm>=4,<5",
]

[project.optional-dependencies]
extras = [
    "matplotlib>=3.9,<4.0",
    "pooch>=1.8.2,<2.0.0",
    "scanpy[leiden]>=1.10.4,<2.0.0",
    "scvelo>=0.3.3,<0.4.0",
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
ipykernel = "^7.1.0"
ruff = "^0.15.12"
mypy = "^2.0.0"
pooch = "^1.8.2"
scanpy = {extras = ["leiden"], version = "^1.10.4"}
pycairo = "^1.27.0"
cairosvg = "^2.7.1"
scvelo = "^0.3.3"
ty = "^0.0.34"
pandas = ">=2.2.3,<3" # >=2.2.3 for cp313 wheels; <3 to avoid 3.0
tqdm = "^4.67.3"
pytest = "^9.0.3"
pytest-cov = "^7.1.0"
nbstripout = "^0.9.1"

[tool.poetry.group.docs.dependencies]
sphinx = ">=8.0.0"
pydata-sphinx-theme = "^0.16.1"
jupyter-sphinx = "^0.5.3"
ipython = "^9.13.0"
furo = "^2025.12.19"
sphinx-copybutton = "^0.5.2"
sphinx-design = "^0.7.0"
squidpy = "^1.8.1"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=cellestial --cov-report=xml:tests/coverage.xml --cov-report=term-missing"

[tool.coverage.run]
data_file = "tests/.coverage"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
