[tool.poetry]
name = "cellestial"
version = "0.14.0"
description = ""
authors = ["Zaf4 <zafermolbio@gmail.com>"]
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
anndata = "^0.12.10"
lets-plot = "^4.9.0"
polars = {extras = ["pyarrow"], version = "^1.38.0"}
scikit-image = "^0.26.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^7.1.0"
ruff = "^0.15.0"
mypy = "^1.13.0"
pooch = "^1.8.2"
scanpy = {extras = ["leiden"], version = "^1.10.4"}
pycairo = "^1.27.0"
cairosvg = "^2.7.1"
scvelo = "^0.3.3"
ty = "^0.0.17"
pandas = "2.2.2" # pinned to avoid 3.0
tqdm = "^4.67.3"

[tool.poetry.group.docs.dependencies]
sphinx = ">=8.0.0"
pydata-sphinx-theme = "^0.16.1"
jupyter-sphinx = "^0.5.3"
ipython = "^9.10.0"
furo = "^2025.12.19"
sphinx-copybutton = "^0.5.2"
sphinx-design = "^0.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"