from cellestial._version import __version__, versions
from cellestial.frames import build_frame
from cellestial.layers import cluster_outlines
from cellestial.single import (
    bar,
    boxplot,
    boxplots,
    dimensional,
    dimensionals,
    dotplot,
    expression,
    expressions,
    heatmap,
    pca,
    pcas,
    plot,
    scatter,
    tsne,
    tsnes,
    umap,
    umaps,
    violin,
    violins,
    xyplot,
    xyplots,
)
from cellestial.util import _add_arrow_axis, get_mapping, retrieve, slice
from cellestial.util.colors import (
    BLUE,
    CHERRY,
    LIGHT_GRAY,
    ORANGE,
    PINK,
    PURPLE,
    RED,
    SNOW,
    TEAL,
    show_colors,
)

__all__ = [
    "BLUE",
    "CHERRY",
    "LIGHT_GRAY",
    "ORANGE",
    "PINK",
    "PURPLE",
    "RED",
    "SNOW",
    "TEAL",
    "__version__",
    "_add_arrow_axis",
    "bar",
    "boxplot",
    "boxplots",
    "build_frame",
    "cluster_outlines",
    "dimensional",
    "dimensionals",
    "dotplot",
    "expression",
    "expressions",
    "get_mapping",
    "heatmap",
    "interactive",
    "pca",
    "pcas",
    "plot",
    "retrieve",
    "scatter",
    "show_colors",
    "slice",
    "tsne",
    "tsnes",
    "umap",
    "umaps",
    "versions",
    "violin",
    "violins",
    "xyplot",
    "xyplots",
]
